# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CookieCrowdSource' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CookieCrowdSource
  pod 'Stripe', '~> 11.2.0'
  pod 'Alamofire', '~> 4.5.0'
  pod 'NVActivityIndicatorView'
  pod 'PusherSwift', '~> 5.0.1'
  pod 'KYDrawerController', '~> 2.0.3'
  pod 'Cosmos', '~> 12.0'
  pod 'Mixpanel-swift', :git=> 'https://github.com/mixpanel/mixpanel-swift.git', :branch=> 'swift4'

  target 'CookieCrowdSourceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CookieCrowdSourceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
