# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CookieCrowdSource' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CookieCrowdSource
  pod 'Stripe'
  pod 'Alamofire', '~> 4.4'
  pod 'NVActivityIndicatorView'
  pod 'PusherSwift', '~> 5.0'

  target 'CookieCrowdSourceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CookieCrowdSourceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
